// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package bem

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/stainless-sdks/bem-go/internal/apijson"
	"github.com/stainless-sdks/bem-go/internal/apiquery"
	"github.com/stainless-sdks/bem-go/internal/requestconfig"
	"github.com/stainless-sdks/bem-go/option"
	"github.com/stainless-sdks/bem-go/packages/pagination"
	"github.com/stainless-sdks/bem-go/packages/param"
	"github.com/stainless-sdks/bem-go/packages/respjson"
)

// Retrieve terminal error events from workflow calls.
//
// Errors are events produced by function steps that failed during processing. A
// single workflow call may produce multiple error events if several steps fail
// independently.
//
// Errors and outputs from the same call are not mutually exclusive: a
// partially-completed workflow may have both.
//
// Use `GET /v3/errors` to list errors across calls, or `GET /v3/errors/{eventID}`
// to retrieve a specific error. To get errors scoped to a single call, filter by
// `callIDs`.
//
// ErrorService contains methods and other services that help with interacting with
// the bem API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewErrorService] method instead.
type ErrorService struct {
	options []option.RequestOption
}

// NewErrorService generates a new service that applies the given options to each
// request. These options are applied after the parent client's options (if there
// is one), and before any request-specific options.
func NewErrorService(opts ...option.RequestOption) (r ErrorService) {
	r = ErrorService{}
	r.options = opts
	return
}

// **Retrieve a single error event by ID.**
//
// Returns `404` if the event does not exist or if it is not an error event (use
// `GET /v3/outputs/{eventID}` for non-error events).
func (r *ErrorService) Get(ctx context.Context, eventID string, opts ...option.RequestOption) (res *ErrorGetResponse, err error) {
	opts = slices.Concat(r.options, opts)
	if eventID == "" {
		err = errors.New("missing required eventID parameter")
		return nil, err
	}
	path := fmt.Sprintf("v3/errors/%s", url.PathEscape(eventID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// **List terminal error events.**
//
// Returns error events produced by failed function calls within workflow
// executions. Non-error output events are excluded; use `GET /v3/outputs` to
// retrieve those.
//
// ## Filtering
//
// Filter by call, workflow, function, or reference ID. Multiple filters are ANDed
// together.
func (r *ErrorService) List(ctx context.Context, query ErrorListParams, opts ...option.RequestOption) (res *pagination.ErrorsPage[ErrorEvent], err error) {
	var raw *http.Response
	opts = slices.Concat(r.options, opts)
	opts = append([]option.RequestOption{option.WithResponseInto(&raw)}, opts...)
	path := "v3/errors"
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, path, query, &res, opts...)
	if err != nil {
		return nil, err
	}
	err = cfg.Execute()
	if err != nil {
		return nil, err
	}
	res.SetPageConfig(cfg, raw)
	return res, nil
}

// **List terminal error events.**
//
// Returns error events produced by failed function calls within workflow
// executions. Non-error output events are excluded; use `GET /v3/outputs` to
// retrieve those.
//
// ## Filtering
//
// Filter by call, workflow, function, or reference ID. Multiple filters are ANDed
// together.
func (r *ErrorService) ListAutoPaging(ctx context.Context, query ErrorListParams, opts ...option.RequestOption) *pagination.ErrorsPageAutoPager[ErrorEvent] {
	return pagination.NewErrorsPageAutoPager(r.List(ctx, query, opts...))
}

type ErrorEvent struct {
	// Unique ID generated by bem to identify the event.
	EventID string `json:"eventID" api:"required"`
	// Unique identifier of function that this event is associated with.
	FunctionID string `json:"functionID" api:"required"`
	// Unique name of function that this event is associated with.
	FunctionName string `json:"functionName" api:"required"`
	// Error message.
	Message string `json:"message" api:"required"`
	// The unique ID you use internally to refer to this data point, propagated from
	// the original function input.
	ReferenceID string `json:"referenceID" api:"required"`
	// Unique identifier of workflow call that this event is associated with.
	CallID string `json:"callID"`
	// Timestamp indicating when the event was created.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// Any of "error".
	EventType ErrorEventEventType `json:"eventType"`
	// Unique identifier of function call that this event is associated with.
	FunctionCallID string `json:"functionCallID"`
	// The attempt number of the function call that created this event. 1 indexed.
	FunctionCallTryNumber int64 `json:"functionCallTryNumber"`
	// Version number of function that this event is associated with.
	FunctionVersionNum int64 `json:"functionVersionNum"`
	// The inbound email that triggered this event.
	InboundEmail InboundEmailEvent  `json:"inboundEmail"`
	Metadata     ErrorEventMetadata `json:"metadata"`
	// Unique identifier of workflow that this event is associated with.
	WorkflowID string `json:"workflowID"`
	// Name of workflow that this event is associated with.
	WorkflowName string `json:"workflowName"`
	// Version number of workflow that this event is associated with.
	WorkflowVersionNum int64 `json:"workflowVersionNum"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		EventID               respjson.Field
		FunctionID            respjson.Field
		FunctionName          respjson.Field
		Message               respjson.Field
		ReferenceID           respjson.Field
		CallID                respjson.Field
		CreatedAt             respjson.Field
		EventType             respjson.Field
		FunctionCallID        respjson.Field
		FunctionCallTryNumber respjson.Field
		FunctionVersionNum    respjson.Field
		InboundEmail          respjson.Field
		Metadata              respjson.Field
		WorkflowID            respjson.Field
		WorkflowName          respjson.Field
		WorkflowVersionNum    respjson.Field
		ExtraFields           map[string]respjson.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ErrorEvent) RawJSON() string { return r.JSON.raw }
func (r *ErrorEvent) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ErrorEventEventType string

const (
	ErrorEventEventTypeError ErrorEventEventType = "error"
)

type ErrorEventMetadata struct {
	DurationFunctionToEventSeconds float64 `json:"durationFunctionToEventSeconds"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		DurationFunctionToEventSeconds respjson.Field
		ExtraFields                    map[string]respjson.Field
		raw                            string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ErrorEventMetadata) RawJSON() string { return r.JSON.raw }
func (r *ErrorEventMetadata) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type InboundEmailEvent struct {
	// The email address of the sender.
	From string `json:"from" api:"required"`
	// The subject of the email.
	Subject string `json:"subject" api:"required"`
	// The email address of the recipient.
	To string `json:"to" api:"required"`
	// The email address of the original intended recipient if the email itself was
	// forwarded.
	DeliveredTo string `json:"deliveredTo"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		From        respjson.Field
		Subject     respjson.Field
		To          respjson.Field
		DeliveredTo respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r InboundEmailEvent) RawJSON() string { return r.JSON.raw }
func (r *InboundEmailEvent) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ErrorGetResponse struct {
	// The error event.
	Error ErrorEvent `json:"error" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Error       respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ErrorGetResponse) RawJSON() string { return r.JSON.raw }
func (r *ErrorGetResponse) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ErrorListParams struct {
	EndingBefore param.Opt[string] `query:"endingBefore,omitzero" json:"-"`
	Limit        param.Opt[int64]  `query:"limit,omitzero" json:"-"`
	// Case-insensitive substring match against `referenceID`.
	ReferenceIDSubstring param.Opt[string] `query:"referenceIDSubstring,omitzero" json:"-"`
	StartingAfter        param.Opt[string] `query:"startingAfter,omitzero" json:"-"`
	// Filter to errors from specific calls.
	CallIDs       []string `query:"callIDs,omitzero" json:"-"`
	FunctionIDs   []string `query:"functionIDs,omitzero" json:"-"`
	FunctionNames []string `query:"functionNames,omitzero" json:"-"`
	ReferenceIDs  []string `query:"referenceIDs,omitzero" json:"-"`
	// Any of "asc", "desc".
	SortOrder     ErrorListParamsSortOrder `query:"sortOrder,omitzero" json:"-"`
	WorkflowIDs   []string                 `query:"workflowIDs,omitzero" json:"-"`
	WorkflowNames []string                 `query:"workflowNames,omitzero" json:"-"`
	paramObj
}

// URLQuery serializes [ErrorListParams]'s query parameters as `url.Values`.
func (r ErrorListParams) URLQuery() (v url.Values, err error) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type ErrorListParamsSortOrder string

const (
	ErrorListParamsSortOrderAsc  ErrorListParamsSortOrder = "asc"
	ErrorListParamsSortOrderDesc ErrorListParamsSortOrder = "desc"
)
