// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package bem

import (
	"encoding/json"
	"time"

	"github.com/bem-team/bem-go-sdk/internal/apijson"
	"github.com/bem-team/bem-go-sdk/option"
	"github.com/bem-team/bem-go-sdk/packages/respjson"
)

// WebhookService contains methods and other services that help with interacting
// with the bem API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewWebhookService] method instead.
type WebhookService struct {
	options []option.RequestOption
}

// NewWebhookService generates a new service that applies the given options to each
// request. These options are applied after the parent client's options (if there
// is one), and before any request-specific options.
func NewWebhookService(opts ...option.RequestOption) (r WebhookService) {
	r = WebhookService{}
	r.options = opts
	return
}

func (r *WebhookService) Unwrap(payload []byte, opts ...option.RequestOption) (*UnwrapWebhookEventUnion, error) {
	res := &UnwrapWebhookEventUnion{}
	err := res.UnmarshalJSON(payload)
	if err != nil {
		return res, err
	}
	return res, nil
}

// V3 event variants that do not exist in the shared `Event` union.
//
// `ExtractEvent` and `ClassifyEvent` are emitted only by V3-era function types
// (`extract` and `classify`). The shared `Event` union in
// `specs/events/models.tsp` predates these types and continues to describe V2 /
// V1-alpha responses verbatim; V3 response payloads add the new variants via the
// `EventV3` union below while keeping every shared variant intact for backward
// compatibility.
type ExtractWebhookEvent struct {
	// Unique ID generated by bem to identify the event.
	EventID string `json:"eventID" api:"required"`
	// Unique identifier of function that this event is associated with.
	FunctionID string `json:"functionID" api:"required"`
	// Unique name of function that this event is associated with.
	FunctionName string `json:"functionName" api:"required"`
	// The number of items that were transformed. Used for batch transformations to
	// indicate how many items were transformed.
	ItemCount int64 `json:"itemCount" api:"required"`
	// The offset of the first item that was transformed. Used for batch
	// transformations to indicate which item in the batch this event corresponds to.
	ItemOffset int64 `json:"itemOffset" api:"required"`
	// The unique ID you use internally to refer to this data point, propagated from
	// the original function input.
	ReferenceID string `json:"referenceID" api:"required"`
	// The transformed content of the input. The structure of this object is defined by
	// the function configuration.
	TransformedContent any `json:"transformedContent" api:"required"`
	// Average confidence score across all extracted fields, in the range [0, 1].
	AvgConfidence float64 `json:"avgConfidence" api:"nullable"`
	// Unique identifier of workflow call that this event is associated with.
	CallID string `json:"callID"`
	// Corrected feedback provided for fine-tuning purposes.
	CorrectedContent ExtractWebhookEventCorrectedContentUnion `json:"correctedContent" api:"nullable"`
	// Timestamp indicating when the event was created.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// Any of "extract".
	EventType ExtractWebhookEventEventType `json:"eventType"`
	// Per-field bounding boxes. A JSON object mapping RFC 6901 JSON Pointer paths
	// (e.g. `"/invoiceNumber"`, `"/items/0/price"`) to the document regions from which
	// each extracted value was sourced.
	FieldBoundingBoxes any `json:"fieldBoundingBoxes"`
	// Per-field confidence scores. A JSON object mapping RFC 6901 JSON Pointer paths
	// (e.g. `"/invoiceNumber"`) to float values in the range [0, 1] indicating the
	// model's confidence in each extracted field value.
	FieldConfidences any `json:"fieldConfidences"`
	// Unique identifier of function call that this event is associated with.
	FunctionCallID string `json:"functionCallID"`
	// The attempt number of the function call that created this event. 1 indexed.
	FunctionCallTryNumber int64 `json:"functionCallTryNumber"`
	// Version number of function that this event is associated with.
	FunctionVersionNum int64 `json:"functionVersionNum"`
	// The inbound email that triggered this event.
	InboundEmail InboundEmailEvent `json:"inboundEmail"`
	// Array of transformation inputs with their types and S3 URLs.
	Inputs []ExtractWebhookEventInput `json:"inputs" api:"nullable"`
	// The input type of the content you're sending for transformation.
	//
	// `jfif` is accepted as an alias for `jpeg` — JFIF is the same format under a
	// different extension — and is normalized to `jpeg`, so responses and webhooks
	// report `jpeg` for a JFIF upload. The undeclared alias `jpg` behaves the same
	// way.
	//
	// Any of "csv", "docx", "email", "heic", "html", "jfif", "jpeg", "json", "heif",
	// "m4a", "mov", "mp3", "mp4", "pdf", "png", "pptx", "text", "wav", "webp", "xls",
	// "xlsx", "xml".
	InputType InputType `json:"inputType"`
	// List of properties that were invalid in the input.
	InvalidProperties []string                    `json:"invalidProperties"`
	Metadata          ExtractWebhookEventMetadata `json:"metadata"`
	// Presigned S3 URL for the input content uploaded to S3.
	S3URL string `json:"s3URL" api:"nullable"`
	// Unique ID for each transformation output generated by bem following Segment's
	// KSUID conventions.
	TransformationID string `json:"transformationID"`
	// Unique identifier of workflow that this event is associated with.
	WorkflowID string `json:"workflowID"`
	// Name of workflow that this event is associated with.
	WorkflowName string `json:"workflowName"`
	// Version number of workflow that this event is associated with.
	WorkflowVersionNum int64 `json:"workflowVersionNum"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		EventID               respjson.Field
		FunctionID            respjson.Field
		FunctionName          respjson.Field
		ItemCount             respjson.Field
		ItemOffset            respjson.Field
		ReferenceID           respjson.Field
		TransformedContent    respjson.Field
		AvgConfidence         respjson.Field
		CallID                respjson.Field
		CorrectedContent      respjson.Field
		CreatedAt             respjson.Field
		EventType             respjson.Field
		FieldBoundingBoxes    respjson.Field
		FieldConfidences      respjson.Field
		FunctionCallID        respjson.Field
		FunctionCallTryNumber respjson.Field
		FunctionVersionNum    respjson.Field
		InboundEmail          respjson.Field
		Inputs                respjson.Field
		InputType             respjson.Field
		InvalidProperties     respjson.Field
		Metadata              respjson.Field
		S3URL                 respjson.Field
		TransformationID      respjson.Field
		WorkflowID            respjson.Field
		WorkflowName          respjson.Field
		WorkflowVersionNum    respjson.Field
		ExtraFields           map[string]respjson.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ExtractWebhookEvent) RawJSON() string { return r.JSON.raw }
func (r *ExtractWebhookEvent) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// ExtractWebhookEventCorrectedContentUnion contains all possible properties and
// values from [ExtractWebhookEventCorrectedContentOutput], [[]any], [string],
// [float64], [bool].
//
// Use the methods beginning with 'As' to cast the union to one of its variants.
//
// If the underlying value is not a json object, one of the following properties
// will be valid: OfAnyArray OfString OfFloat OfBool]
type ExtractWebhookEventCorrectedContentUnion struct {
	// This field will be present if the value is a [[]any] instead of an object.
	OfAnyArray []any `json:",inline"`
	// This field will be present if the value is a [string] instead of an object.
	OfString string `json:",inline"`
	// This field will be present if the value is a [float64] instead of an object.
	OfFloat float64 `json:",inline"`
	// This field will be present if the value is a [bool] instead of an object.
	OfBool bool `json:",inline"`
	// This field is from variant [ExtractWebhookEventCorrectedContentOutput].
	Output []AnyTypeUnion `json:"output"`
	JSON   struct {
		OfAnyArray respjson.Field
		OfString   respjson.Field
		OfFloat    respjson.Field
		OfBool     respjson.Field
		Output     respjson.Field
		raw        string
	} `json:"-"`
}

func (u ExtractWebhookEventCorrectedContentUnion) AsExtractWebhookEventCorrectedContentOutput() (v ExtractWebhookEventCorrectedContentOutput) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u ExtractWebhookEventCorrectedContentUnion) AsAnyArray() (v []any) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u ExtractWebhookEventCorrectedContentUnion) AsString() (v string) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u ExtractWebhookEventCorrectedContentUnion) AsFloat() (v float64) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u ExtractWebhookEventCorrectedContentUnion) AsBool() (v bool) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

// Returns the unmodified JSON received from the API
func (u ExtractWebhookEventCorrectedContentUnion) RawJSON() string { return u.JSON.raw }

func (r *ExtractWebhookEventCorrectedContentUnion) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ExtractWebhookEventCorrectedContentOutput struct {
	Output []AnyTypeUnion `json:"output" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Output      respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ExtractWebhookEventCorrectedContentOutput) RawJSON() string { return r.JSON.raw }
func (r *ExtractWebhookEventCorrectedContentOutput) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ExtractWebhookEventEventType string

const (
	ExtractWebhookEventEventTypeExtract ExtractWebhookEventEventType = "extract"
)

type ExtractWebhookEventInput struct {
	InputContent     string `json:"inputContent" api:"nullable"`
	InputType        string `json:"inputType" api:"nullable"`
	JsonInputContent any    `json:"jsonInputContent" api:"nullable"`
	S3URL            string `json:"s3URL" api:"nullable"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		InputContent     respjson.Field
		InputType        respjson.Field
		JsonInputContent respjson.Field
		S3URL            respjson.Field
		ExtraFields      map[string]respjson.Field
		raw              string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ExtractWebhookEventInput) RawJSON() string { return r.JSON.raw }
func (r *ExtractWebhookEventInput) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ExtractWebhookEventMetadata struct {
	DurationFunctionToEventSeconds float64 `json:"durationFunctionToEventSeconds"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		DurationFunctionToEventSeconds respjson.Field
		ExtraFields                    map[string]respjson.Field
		raw                            string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ExtractWebhookEventMetadata) RawJSON() string { return r.JSON.raw }
func (r *ExtractWebhookEventMetadata) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ClassifyWebhookEvent struct {
	// The classification chosen by the classify function.
	Choice string `json:"choice" api:"required"`
	// Unique ID generated by bem to identify the event.
	EventID string `json:"eventID" api:"required"`
	// Unique identifier of function that this event is associated with.
	FunctionID string `json:"functionID" api:"required"`
	// Unique name of function that this event is associated with.
	FunctionName string `json:"functionName" api:"required"`
	// The unique ID you use internally to refer to this data point, propagated from
	// the original function input.
	ReferenceID string `json:"referenceID" api:"required"`
	// Unique identifier of workflow call that this event is associated with.
	CallID string `json:"callID"`
	// Timestamp indicating when the event was created.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// Any of "classify".
	EventType ClassifyWebhookEventEventType `json:"eventType"`
	// Unique identifier of function call that this event is associated with.
	FunctionCallID string `json:"functionCallID"`
	// The attempt number of the function call that created this event. 1 indexed.
	FunctionCallTryNumber int64 `json:"functionCallTryNumber"`
	// Version number of function that this event is associated with.
	FunctionVersionNum int64 `json:"functionVersionNum"`
	// The inbound email that triggered this event.
	InboundEmail InboundEmailEvent            `json:"inboundEmail"`
	Metadata     ClassifyWebhookEventMetadata `json:"metadata"`
	// The presigned S3 URL of the file that was classified.
	S3URL string `json:"s3URL"`
	// Unique identifier of workflow that this event is associated with.
	WorkflowID string `json:"workflowID"`
	// Name of workflow that this event is associated with.
	WorkflowName string `json:"workflowName"`
	// Version number of workflow that this event is associated with.
	WorkflowVersionNum int64 `json:"workflowVersionNum"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Choice                respjson.Field
		EventID               respjson.Field
		FunctionID            respjson.Field
		FunctionName          respjson.Field
		ReferenceID           respjson.Field
		CallID                respjson.Field
		CreatedAt             respjson.Field
		EventType             respjson.Field
		FunctionCallID        respjson.Field
		FunctionCallTryNumber respjson.Field
		FunctionVersionNum    respjson.Field
		InboundEmail          respjson.Field
		Metadata              respjson.Field
		S3URL                 respjson.Field
		WorkflowID            respjson.Field
		WorkflowName          respjson.Field
		WorkflowVersionNum    respjson.Field
		ExtraFields           map[string]respjson.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ClassifyWebhookEvent) RawJSON() string { return r.JSON.raw }
func (r *ClassifyWebhookEvent) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ClassifyWebhookEventEventType string

const (
	ClassifyWebhookEventEventTypeClassify ClassifyWebhookEventEventType = "classify"
)

type ClassifyWebhookEventMetadata struct {
	DurationFunctionToEventSeconds float64 `json:"durationFunctionToEventSeconds"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		DurationFunctionToEventSeconds respjson.Field
		ExtraFields                    map[string]respjson.Field
		raw                            string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ClassifyWebhookEventMetadata) RawJSON() string { return r.JSON.raw }
func (r *ClassifyWebhookEventMetadata) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Emitted when a `parse` function completes. Reuses the `extract` event shape on
// the wire — both wrap a Transformation and downstream consumers care about the
// same `transformedContent` payload — but uses a distinct `eventType`
// discriminator so receivers can dispatch on the function type that produced it.
type ParseWebhookEvent struct {
	// Unique ID generated by bem to identify the event.
	EventID string `json:"eventID" api:"required"`
	// Unique identifier of function that this event is associated with.
	FunctionID string `json:"functionID" api:"required"`
	// Unique name of function that this event is associated with.
	FunctionName string `json:"functionName" api:"required"`
	// The number of items that were parsed. Used for batch parsing to indicate how
	// many items were parsed.
	ItemCount int64 `json:"itemCount" api:"required"`
	// The offset of the first item that was parsed. Used for batch parsing to indicate
	// which item in the batch this event corresponds to.
	ItemOffset int64 `json:"itemOffset" api:"required"`
	// The unique ID you use internally to refer to this data point, propagated from
	// the original function input.
	ReferenceID string `json:"referenceID" api:"required"`
	// The parsed content of the input. Top-level keys are `sections`, `entities`, and
	// `relationships`; the precise shape is determined by the parse function's
	// configuration.
	TransformedContent any `json:"transformedContent" api:"required"`
	// Average confidence score across all parsed fields, in the range [0, 1].
	AvgConfidence float64 `json:"avgConfidence" api:"nullable"`
	// Unique identifier of workflow call that this event is associated with.
	CallID string `json:"callID"`
	// Corrected feedback provided for fine-tuning purposes.
	CorrectedContent ParseWebhookEventCorrectedContentUnion `json:"correctedContent" api:"nullable"`
	// Timestamp indicating when the event was created.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// Any of "parse".
	EventType ParseWebhookEventEventType `json:"eventType"`
	// Per-field bounding boxes. A JSON object mapping RFC 6901 JSON Pointer paths to
	// the document regions from which each parsed value was sourced.
	FieldBoundingBoxes any `json:"fieldBoundingBoxes"`
	// Per-field confidence scores. A JSON object mapping RFC 6901 JSON Pointer paths
	// to float values in the range [0, 1] indicating the model's confidence in each
	// parsed field value.
	FieldConfidences any `json:"fieldConfidences"`
	// Unique identifier of function call that this event is associated with.
	FunctionCallID string `json:"functionCallID"`
	// The attempt number of the function call that created this event. 1 indexed.
	FunctionCallTryNumber int64 `json:"functionCallTryNumber"`
	// Version number of function that this event is associated with.
	FunctionVersionNum int64 `json:"functionVersionNum"`
	// The inbound email that triggered this event.
	InboundEmail InboundEmailEvent `json:"inboundEmail"`
	// Array of parse inputs with their types and S3 URLs.
	Inputs []ParseWebhookEventInput `json:"inputs" api:"nullable"`
	// The input type of the content you're sending for transformation.
	//
	// `jfif` is accepted as an alias for `jpeg` — JFIF is the same format under a
	// different extension — and is normalized to `jpeg`, so responses and webhooks
	// report `jpeg` for a JFIF upload. The undeclared alias `jpg` behaves the same
	// way.
	//
	// Any of "csv", "docx", "email", "heic", "html", "jfif", "jpeg", "json", "heif",
	// "m4a", "mov", "mp3", "mp4", "pdf", "png", "pptx", "text", "wav", "webp", "xls",
	// "xlsx", "xml".
	InputType InputType `json:"inputType"`
	// List of properties that were invalid in the input.
	InvalidProperties []string                  `json:"invalidProperties"`
	Metadata          ParseWebhookEventMetadata `json:"metadata"`
	// Presigned S3 URL for the input content uploaded to S3.
	S3URL string `json:"s3URL" api:"nullable"`
	// Unique ID for each transformation output generated by bem following Segment's
	// KSUID conventions.
	TransformationID string `json:"transformationID"`
	// Unique identifier of workflow that this event is associated with.
	WorkflowID string `json:"workflowID"`
	// Name of workflow that this event is associated with.
	WorkflowName string `json:"workflowName"`
	// Version number of workflow that this event is associated with.
	WorkflowVersionNum int64 `json:"workflowVersionNum"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		EventID               respjson.Field
		FunctionID            respjson.Field
		FunctionName          respjson.Field
		ItemCount             respjson.Field
		ItemOffset            respjson.Field
		ReferenceID           respjson.Field
		TransformedContent    respjson.Field
		AvgConfidence         respjson.Field
		CallID                respjson.Field
		CorrectedContent      respjson.Field
		CreatedAt             respjson.Field
		EventType             respjson.Field
		FieldBoundingBoxes    respjson.Field
		FieldConfidences      respjson.Field
		FunctionCallID        respjson.Field
		FunctionCallTryNumber respjson.Field
		FunctionVersionNum    respjson.Field
		InboundEmail          respjson.Field
		Inputs                respjson.Field
		InputType             respjson.Field
		InvalidProperties     respjson.Field
		Metadata              respjson.Field
		S3URL                 respjson.Field
		TransformationID      respjson.Field
		WorkflowID            respjson.Field
		WorkflowName          respjson.Field
		WorkflowVersionNum    respjson.Field
		ExtraFields           map[string]respjson.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ParseWebhookEvent) RawJSON() string { return r.JSON.raw }
func (r *ParseWebhookEvent) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// ParseWebhookEventCorrectedContentUnion contains all possible properties and
// values from [ParseWebhookEventCorrectedContentOutput], [[]any], [string],
// [float64], [bool].
//
// Use the methods beginning with 'As' to cast the union to one of its variants.
//
// If the underlying value is not a json object, one of the following properties
// will be valid: OfAnyArray OfString OfFloat OfBool]
type ParseWebhookEventCorrectedContentUnion struct {
	// This field will be present if the value is a [[]any] instead of an object.
	OfAnyArray []any `json:",inline"`
	// This field will be present if the value is a [string] instead of an object.
	OfString string `json:",inline"`
	// This field will be present if the value is a [float64] instead of an object.
	OfFloat float64 `json:",inline"`
	// This field will be present if the value is a [bool] instead of an object.
	OfBool bool `json:",inline"`
	// This field is from variant [ParseWebhookEventCorrectedContentOutput].
	Output []AnyTypeUnion `json:"output"`
	JSON   struct {
		OfAnyArray respjson.Field
		OfString   respjson.Field
		OfFloat    respjson.Field
		OfBool     respjson.Field
		Output     respjson.Field
		raw        string
	} `json:"-"`
}

func (u ParseWebhookEventCorrectedContentUnion) AsParseWebhookEventCorrectedContentOutput() (v ParseWebhookEventCorrectedContentOutput) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u ParseWebhookEventCorrectedContentUnion) AsAnyArray() (v []any) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u ParseWebhookEventCorrectedContentUnion) AsString() (v string) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u ParseWebhookEventCorrectedContentUnion) AsFloat() (v float64) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u ParseWebhookEventCorrectedContentUnion) AsBool() (v bool) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

// Returns the unmodified JSON received from the API
func (u ParseWebhookEventCorrectedContentUnion) RawJSON() string { return u.JSON.raw }

func (r *ParseWebhookEventCorrectedContentUnion) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ParseWebhookEventCorrectedContentOutput struct {
	Output []AnyTypeUnion `json:"output" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Output      respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ParseWebhookEventCorrectedContentOutput) RawJSON() string { return r.JSON.raw }
func (r *ParseWebhookEventCorrectedContentOutput) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ParseWebhookEventEventType string

const (
	ParseWebhookEventEventTypeParse ParseWebhookEventEventType = "parse"
)

type ParseWebhookEventInput struct {
	InputContent     string `json:"inputContent" api:"nullable"`
	InputType        string `json:"inputType" api:"nullable"`
	JsonInputContent any    `json:"jsonInputContent" api:"nullable"`
	S3URL            string `json:"s3URL" api:"nullable"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		InputContent     respjson.Field
		InputType        respjson.Field
		JsonInputContent respjson.Field
		S3URL            respjson.Field
		ExtraFields      map[string]respjson.Field
		raw              string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ParseWebhookEventInput) RawJSON() string { return r.JSON.raw }
func (r *ParseWebhookEventInput) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ParseWebhookEventMetadata struct {
	DurationFunctionToEventSeconds float64 `json:"durationFunctionToEventSeconds"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		DurationFunctionToEventSeconds respjson.Field
		ExtraFields                    map[string]respjson.Field
		raw                            string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ParseWebhookEventMetadata) RawJSON() string { return r.JSON.raw }
func (r *ParseWebhookEventMetadata) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type SplitCollectionWebhookEvent struct {
	// Unique ID generated by bem to identify the event.
	EventID string `json:"eventID" api:"required"`
	// Unique identifier of function that this event is associated with.
	FunctionID string `json:"functionID" api:"required"`
	// Unique name of function that this event is associated with.
	FunctionName string `json:"functionName" api:"required"`
	// Any of "print_page", "semantic_page".
	OutputType      SplitCollectionWebhookEventOutputType      `json:"outputType" api:"required"`
	PrintPageOutput SplitCollectionWebhookEventPrintPageOutput `json:"printPageOutput" api:"required"`
	// The unique ID you use internally to refer to this data point, propagated from
	// the original function input.
	ReferenceID        string                                        `json:"referenceID" api:"required"`
	SemanticPageOutput SplitCollectionWebhookEventSemanticPageOutput `json:"semanticPageOutput" api:"required"`
	// Unique identifier of workflow call that this event is associated with.
	CallID string `json:"callID"`
	// Timestamp indicating when the event was created.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// Any of "split_collection".
	EventType SplitCollectionWebhookEventEventType `json:"eventType"`
	// Unique identifier of function call that this event is associated with.
	FunctionCallID string `json:"functionCallID"`
	// The attempt number of the function call that created this event. 1 indexed.
	FunctionCallTryNumber int64 `json:"functionCallTryNumber"`
	// Version number of function that this event is associated with.
	FunctionVersionNum int64 `json:"functionVersionNum"`
	// The inbound email that triggered this event.
	InboundEmail InboundEmailEvent                   `json:"inboundEmail"`
	Metadata     SplitCollectionWebhookEventMetadata `json:"metadata"`
	// Unique identifier of workflow that this event is associated with.
	WorkflowID string `json:"workflowID"`
	// Name of workflow that this event is associated with.
	WorkflowName string `json:"workflowName"`
	// Version number of workflow that this event is associated with.
	WorkflowVersionNum int64 `json:"workflowVersionNum"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		EventID               respjson.Field
		FunctionID            respjson.Field
		FunctionName          respjson.Field
		OutputType            respjson.Field
		PrintPageOutput       respjson.Field
		ReferenceID           respjson.Field
		SemanticPageOutput    respjson.Field
		CallID                respjson.Field
		CreatedAt             respjson.Field
		EventType             respjson.Field
		FunctionCallID        respjson.Field
		FunctionCallTryNumber respjson.Field
		FunctionVersionNum    respjson.Field
		InboundEmail          respjson.Field
		Metadata              respjson.Field
		WorkflowID            respjson.Field
		WorkflowName          respjson.Field
		WorkflowVersionNum    respjson.Field
		ExtraFields           map[string]respjson.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SplitCollectionWebhookEvent) RawJSON() string { return r.JSON.raw }
func (r *SplitCollectionWebhookEvent) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type SplitCollectionWebhookEventOutputType string

const (
	SplitCollectionWebhookEventOutputTypePrintPage    SplitCollectionWebhookEventOutputType = "print_page"
	SplitCollectionWebhookEventOutputTypeSemanticPage SplitCollectionWebhookEventOutputType = "semantic_page"
)

type SplitCollectionWebhookEventPrintPageOutput struct {
	ItemCount int64                                            `json:"itemCount"`
	Items     []SplitCollectionWebhookEventPrintPageOutputItem `json:"items"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		ItemCount   respjson.Field
		Items       respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SplitCollectionWebhookEventPrintPageOutput) RawJSON() string { return r.JSON.raw }
func (r *SplitCollectionWebhookEventPrintPageOutput) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type SplitCollectionWebhookEventPrintPageOutputItem struct {
	ItemOffset      int64  `json:"itemOffset"`
	ItemReferenceID string `json:"itemReferenceID"`
	S3URL           string `json:"s3URL"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		ItemOffset      respjson.Field
		ItemReferenceID respjson.Field
		S3URL           respjson.Field
		ExtraFields     map[string]respjson.Field
		raw             string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SplitCollectionWebhookEventPrintPageOutputItem) RawJSON() string { return r.JSON.raw }
func (r *SplitCollectionWebhookEventPrintPageOutputItem) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type SplitCollectionWebhookEventSemanticPageOutput struct {
	ItemCount int64                                               `json:"itemCount"`
	Items     []SplitCollectionWebhookEventSemanticPageOutputItem `json:"items"`
	PageCount int64                                               `json:"pageCount"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		ItemCount   respjson.Field
		Items       respjson.Field
		PageCount   respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SplitCollectionWebhookEventSemanticPageOutput) RawJSON() string { return r.JSON.raw }
func (r *SplitCollectionWebhookEventSemanticPageOutput) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type SplitCollectionWebhookEventSemanticPageOutputItem struct {
	ItemClass       string `json:"itemClass"`
	ItemClassCount  int64  `json:"itemClassCount"`
	ItemClassOffset int64  `json:"itemClassOffset"`
	ItemOffset      int64  `json:"itemOffset"`
	ItemReferenceID string `json:"itemReferenceID"`
	PageEnd         int64  `json:"pageEnd"`
	PageStart       int64  `json:"pageStart"`
	S3URL           string `json:"s3URL"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		ItemClass       respjson.Field
		ItemClassCount  respjson.Field
		ItemClassOffset respjson.Field
		ItemOffset      respjson.Field
		ItemReferenceID respjson.Field
		PageEnd         respjson.Field
		PageStart       respjson.Field
		S3URL           respjson.Field
		ExtraFields     map[string]respjson.Field
		raw             string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SplitCollectionWebhookEventSemanticPageOutputItem) RawJSON() string { return r.JSON.raw }
func (r *SplitCollectionWebhookEventSemanticPageOutputItem) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type SplitCollectionWebhookEventEventType string

const (
	SplitCollectionWebhookEventEventTypeSplitCollection SplitCollectionWebhookEventEventType = "split_collection"
)

type SplitCollectionWebhookEventMetadata struct {
	DurationFunctionToEventSeconds float64 `json:"durationFunctionToEventSeconds"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		DurationFunctionToEventSeconds respjson.Field
		ExtraFields                    map[string]respjson.Field
		raw                            string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SplitCollectionWebhookEventMetadata) RawJSON() string { return r.JSON.raw }
func (r *SplitCollectionWebhookEventMetadata) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type SplitItemWebhookEvent struct {
	// Unique ID generated by bem to identify the event.
	EventID string `json:"eventID" api:"required"`
	// Unique identifier of function that this event is associated with.
	FunctionID string `json:"functionID" api:"required"`
	// Unique name of function that this event is associated with.
	FunctionName string `json:"functionName" api:"required"`
	// Any of "print_page", "semantic_page".
	OutputType SplitItemWebhookEventOutputType `json:"outputType" api:"required"`
	// The unique ID you use internally to refer to this data point, propagated from
	// the original function input.
	ReferenceID string `json:"referenceID" api:"required"`
	// Unique identifier of workflow call that this event is associated with.
	CallID string `json:"callID"`
	// Timestamp indicating when the event was created.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// Any of "split_item".
	EventType SplitItemWebhookEventEventType `json:"eventType"`
	// Unique identifier of function call that this event is associated with.
	FunctionCallID string `json:"functionCallID"`
	// The attempt number of the function call that created this event. 1 indexed.
	FunctionCallTryNumber int64 `json:"functionCallTryNumber"`
	// Version number of function that this event is associated with.
	FunctionVersionNum int64 `json:"functionVersionNum"`
	// The inbound email that triggered this event.
	InboundEmail       InboundEmailEvent                       `json:"inboundEmail"`
	Metadata           SplitItemWebhookEventMetadata           `json:"metadata"`
	PrintPageOutput    SplitItemWebhookEventPrintPageOutput    `json:"printPageOutput"`
	SemanticPageOutput SplitItemWebhookEventSemanticPageOutput `json:"semanticPageOutput"`
	// Unique identifier of workflow that this event is associated with.
	WorkflowID string `json:"workflowID"`
	// Name of workflow that this event is associated with.
	WorkflowName string `json:"workflowName"`
	// Version number of workflow that this event is associated with.
	WorkflowVersionNum int64 `json:"workflowVersionNum"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		EventID               respjson.Field
		FunctionID            respjson.Field
		FunctionName          respjson.Field
		OutputType            respjson.Field
		ReferenceID           respjson.Field
		CallID                respjson.Field
		CreatedAt             respjson.Field
		EventType             respjson.Field
		FunctionCallID        respjson.Field
		FunctionCallTryNumber respjson.Field
		FunctionVersionNum    respjson.Field
		InboundEmail          respjson.Field
		Metadata              respjson.Field
		PrintPageOutput       respjson.Field
		SemanticPageOutput    respjson.Field
		WorkflowID            respjson.Field
		WorkflowName          respjson.Field
		WorkflowVersionNum    respjson.Field
		ExtraFields           map[string]respjson.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SplitItemWebhookEvent) RawJSON() string { return r.JSON.raw }
func (r *SplitItemWebhookEvent) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type SplitItemWebhookEventOutputType string

const (
	SplitItemWebhookEventOutputTypePrintPage    SplitItemWebhookEventOutputType = "print_page"
	SplitItemWebhookEventOutputTypeSemanticPage SplitItemWebhookEventOutputType = "semantic_page"
)

type SplitItemWebhookEventEventType string

const (
	SplitItemWebhookEventEventTypeSplitItem SplitItemWebhookEventEventType = "split_item"
)

type SplitItemWebhookEventMetadata struct {
	DurationFunctionToEventSeconds float64 `json:"durationFunctionToEventSeconds"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		DurationFunctionToEventSeconds respjson.Field
		ExtraFields                    map[string]respjson.Field
		raw                            string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SplitItemWebhookEventMetadata) RawJSON() string { return r.JSON.raw }
func (r *SplitItemWebhookEventMetadata) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type SplitItemWebhookEventPrintPageOutput struct {
	CollectionReferenceID string `json:"collectionReferenceID"`
	ItemCount             int64  `json:"itemCount"`
	ItemOffset            int64  `json:"itemOffset"`
	S3URL                 string `json:"s3URL"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		CollectionReferenceID respjson.Field
		ItemCount             respjson.Field
		ItemOffset            respjson.Field
		S3URL                 respjson.Field
		ExtraFields           map[string]respjson.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SplitItemWebhookEventPrintPageOutput) RawJSON() string { return r.JSON.raw }
func (r *SplitItemWebhookEventPrintPageOutput) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type SplitItemWebhookEventSemanticPageOutput struct {
	CollectionReferenceID string `json:"collectionReferenceID"`
	ItemClass             string `json:"itemClass"`
	ItemClassCount        int64  `json:"itemClassCount"`
	ItemClassOffset       int64  `json:"itemClassOffset"`
	ItemCount             int64  `json:"itemCount"`
	ItemOffset            int64  `json:"itemOffset"`
	PageCount             int64  `json:"pageCount"`
	PageEnd               int64  `json:"pageEnd"`
	PageStart             int64  `json:"pageStart"`
	S3URL                 string `json:"s3URL"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		CollectionReferenceID respjson.Field
		ItemClass             respjson.Field
		ItemClassCount        respjson.Field
		ItemClassOffset       respjson.Field
		ItemCount             respjson.Field
		ItemOffset            respjson.Field
		PageCount             respjson.Field
		PageEnd               respjson.Field
		PageStart             respjson.Field
		S3URL                 respjson.Field
		ExtraFields           map[string]respjson.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SplitItemWebhookEventSemanticPageOutput) RawJSON() string { return r.JSON.raw }
func (r *SplitItemWebhookEventSemanticPageOutput) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type JoinWebhookEvent struct {
	// Unique ID generated by bem to identify the event.
	EventID string `json:"eventID" api:"required"`
	// Unique identifier of function that this event is associated with.
	FunctionID string `json:"functionID" api:"required"`
	// Unique name of function that this event is associated with.
	FunctionName string `json:"functionName" api:"required"`
	// List of properties that were invalid in the input.
	InvalidProperties []string `json:"invalidProperties" api:"required"`
	// The items that were joined.
	Items []JoinWebhookEventItem `json:"items" api:"required"`
	// The type of join that was performed.
	//
	// Any of "standard".
	JoinType JoinWebhookEventJoinType `json:"joinType" api:"required"`
	// The unique ID you use internally to refer to this data point, propagated from
	// the original function input.
	ReferenceID string `json:"referenceID" api:"required"`
	// The transformed content of the input. The structure of this object is defined by
	// the function configuration.
	TransformedContent any `json:"transformedContent" api:"required"`
	// Average confidence score across all extracted fields, in the range [0, 1].
	AvgConfidence float64 `json:"avgConfidence" api:"nullable"`
	// Unique identifier of workflow call that this event is associated with.
	CallID string `json:"callID"`
	// Timestamp indicating when the event was created.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// Any of "join".
	EventType JoinWebhookEventEventType `json:"eventType"`
	// Per-field confidence scores. A JSON object mapping RFC 6901 JSON Pointer paths
	// (e.g. `"/invoiceNumber"`) to float values in the range [0, 1] indicating the
	// model's confidence in each extracted field value.
	FieldConfidences any `json:"fieldConfidences"`
	// Unique identifier of function call that this event is associated with.
	FunctionCallID string `json:"functionCallID"`
	// The attempt number of the function call that created this event. 1 indexed.
	FunctionCallTryNumber int64 `json:"functionCallTryNumber"`
	// Version number of function that this event is associated with.
	FunctionVersionNum int64 `json:"functionVersionNum"`
	// The inbound email that triggered this event.
	InboundEmail InboundEmailEvent        `json:"inboundEmail"`
	Metadata     JoinWebhookEventMetadata `json:"metadata"`
	// Unique ID for each transformation output generated by bem following Segment's
	// KSUID conventions.
	TransformationID string `json:"transformationID"`
	// Unique identifier of workflow that this event is associated with.
	WorkflowID string `json:"workflowID"`
	// Name of workflow that this event is associated with.
	WorkflowName string `json:"workflowName"`
	// Version number of workflow that this event is associated with.
	WorkflowVersionNum int64 `json:"workflowVersionNum"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		EventID               respjson.Field
		FunctionID            respjson.Field
		FunctionName          respjson.Field
		InvalidProperties     respjson.Field
		Items                 respjson.Field
		JoinType              respjson.Field
		ReferenceID           respjson.Field
		TransformedContent    respjson.Field
		AvgConfidence         respjson.Field
		CallID                respjson.Field
		CreatedAt             respjson.Field
		EventType             respjson.Field
		FieldConfidences      respjson.Field
		FunctionCallID        respjson.Field
		FunctionCallTryNumber respjson.Field
		FunctionVersionNum    respjson.Field
		InboundEmail          respjson.Field
		Metadata              respjson.Field
		TransformationID      respjson.Field
		WorkflowID            respjson.Field
		WorkflowName          respjson.Field
		WorkflowVersionNum    respjson.Field
		ExtraFields           map[string]respjson.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r JoinWebhookEvent) RawJSON() string { return r.JSON.raw }
func (r *JoinWebhookEvent) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type JoinWebhookEventItem struct {
	// The number of items that were transformed.
	ItemCount int64 `json:"itemCount" api:"required"`
	// The offset of the first item that was transformed. Used for batch
	// transformations to indicate which item in the batch this event corresponds to.
	ItemOffset int64 `json:"itemOffset" api:"required"`
	// The unique ID you use internally to refer to this data point.
	ItemReferenceID string `json:"itemReferenceID" api:"required"`
	// The presigned S3 URL of the file that was joined.
	S3URL string `json:"s3URL"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		ItemCount       respjson.Field
		ItemOffset      respjson.Field
		ItemReferenceID respjson.Field
		S3URL           respjson.Field
		ExtraFields     map[string]respjson.Field
		raw             string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r JoinWebhookEventItem) RawJSON() string { return r.JSON.raw }
func (r *JoinWebhookEventItem) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// The type of join that was performed.
type JoinWebhookEventJoinType string

const (
	JoinWebhookEventJoinTypeStandard JoinWebhookEventJoinType = "standard"
)

type JoinWebhookEventEventType string

const (
	JoinWebhookEventEventTypeJoin JoinWebhookEventEventType = "join"
)

type JoinWebhookEventMetadata struct {
	DurationFunctionToEventSeconds float64 `json:"durationFunctionToEventSeconds"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		DurationFunctionToEventSeconds respjson.Field
		ExtraFields                    map[string]respjson.Field
		raw                            string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r JoinWebhookEventMetadata) RawJSON() string { return r.JSON.raw }
func (r *JoinWebhookEventMetadata) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type EnrichWebhookEvent struct {
	// The enriched content produced by the enrich function. Contains the input data
	// augmented with results from semantic search against collections.
	EnrichedContent any `json:"enrichedContent" api:"required"`
	// Unique ID generated by bem to identify the event.
	EventID string `json:"eventID" api:"required"`
	// Unique identifier of function that this event is associated with.
	FunctionID string `json:"functionID" api:"required"`
	// Unique name of function that this event is associated with.
	FunctionName string `json:"functionName" api:"required"`
	// The unique ID you use internally to refer to this data point, propagated from
	// the original function input.
	ReferenceID string `json:"referenceID" api:"required"`
	// Unique identifier of workflow call that this event is associated with.
	CallID string `json:"callID"`
	// Timestamp indicating when the event was created.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// Any of "enrich".
	EventType EnrichWebhookEventEventType `json:"eventType"`
	// Unique identifier of function call that this event is associated with.
	FunctionCallID string `json:"functionCallID"`
	// The attempt number of the function call that created this event. 1 indexed.
	FunctionCallTryNumber int64 `json:"functionCallTryNumber"`
	// Version number of function that this event is associated with.
	FunctionVersionNum int64 `json:"functionVersionNum"`
	// The client-submitted ground-truth re-ranking of this output's candidates, if any
	// (see `POST /v3/events/{eventID}/enrich-feedback`). Omitted when not set.
	GroundTruth any `json:"groundTruth"`
	// The inbound email that triggered this event.
	InboundEmail InboundEmailEvent          `json:"inboundEmail"`
	Metadata     EnrichWebhookEventMetadata `json:"metadata"`
	// Unique identifier of workflow that this event is associated with.
	WorkflowID string `json:"workflowID"`
	// Name of workflow that this event is associated with.
	WorkflowName string `json:"workflowName"`
	// Version number of workflow that this event is associated with.
	WorkflowVersionNum int64 `json:"workflowVersionNum"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		EnrichedContent       respjson.Field
		EventID               respjson.Field
		FunctionID            respjson.Field
		FunctionName          respjson.Field
		ReferenceID           respjson.Field
		CallID                respjson.Field
		CreatedAt             respjson.Field
		EventType             respjson.Field
		FunctionCallID        respjson.Field
		FunctionCallTryNumber respjson.Field
		FunctionVersionNum    respjson.Field
		GroundTruth           respjson.Field
		InboundEmail          respjson.Field
		Metadata              respjson.Field
		WorkflowID            respjson.Field
		WorkflowName          respjson.Field
		WorkflowVersionNum    respjson.Field
		ExtraFields           map[string]respjson.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r EnrichWebhookEvent) RawJSON() string { return r.JSON.raw }
func (r *EnrichWebhookEvent) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type EnrichWebhookEventEventType string

const (
	EnrichWebhookEventEventTypeEnrich EnrichWebhookEventEventType = "enrich"
)

type EnrichWebhookEventMetadata struct {
	DurationFunctionToEventSeconds float64 `json:"durationFunctionToEventSeconds"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		DurationFunctionToEventSeconds respjson.Field
		ExtraFields                    map[string]respjson.Field
		raw                            string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r EnrichWebhookEventMetadata) RawJSON() string { return r.JSON.raw }
func (r *EnrichWebhookEventMetadata) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Emitted by `payload_shaping` functions, which restructure JSON payloads using
// JMESPath expressions configured on the function. The shaped result is carried in
// `transformedContent`.
type PayloadShapingWebhookEvent struct {
	// Unique ID generated by bem to identify the event.
	EventID string `json:"eventID" api:"required"`
	// Unique identifier of function that this event is associated with.
	FunctionID string `json:"functionID" api:"required"`
	// Unique name of function that this event is associated with.
	FunctionName string `json:"functionName" api:"required"`
	// The unique ID you use internally to refer to this data point, propagated from
	// the original function input.
	ReferenceID string `json:"referenceID" api:"required"`
	// The reshaped payload produced by applying the function's JMESPath expressions to
	// the input data.
	TransformedContent any `json:"transformedContent" api:"required"`
	// Unique identifier of workflow call that this event is associated with.
	CallID string `json:"callID"`
	// Timestamp indicating when the event was created.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// Any of "payload_shaping".
	EventType PayloadShapingWebhookEventEventType `json:"eventType"`
	// Unique identifier of function call that this event is associated with.
	FunctionCallID string `json:"functionCallID"`
	// The attempt number of the function call that created this event. 1 indexed.
	FunctionCallTryNumber int64 `json:"functionCallTryNumber"`
	// Version number of function that this event is associated with.
	FunctionVersionNum int64 `json:"functionVersionNum"`
	// The inbound email that triggered this event.
	InboundEmail InboundEmailEvent                  `json:"inboundEmail"`
	Metadata     PayloadShapingWebhookEventMetadata `json:"metadata"`
	// Unique identifier of workflow that this event is associated with.
	WorkflowID string `json:"workflowID"`
	// Name of workflow that this event is associated with.
	WorkflowName string `json:"workflowName"`
	// Version number of workflow that this event is associated with.
	WorkflowVersionNum int64 `json:"workflowVersionNum"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		EventID               respjson.Field
		FunctionID            respjson.Field
		FunctionName          respjson.Field
		ReferenceID           respjson.Field
		TransformedContent    respjson.Field
		CallID                respjson.Field
		CreatedAt             respjson.Field
		EventType             respjson.Field
		FunctionCallID        respjson.Field
		FunctionCallTryNumber respjson.Field
		FunctionVersionNum    respjson.Field
		InboundEmail          respjson.Field
		Metadata              respjson.Field
		WorkflowID            respjson.Field
		WorkflowName          respjson.Field
		WorkflowVersionNum    respjson.Field
		ExtraFields           map[string]respjson.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r PayloadShapingWebhookEvent) RawJSON() string { return r.JSON.raw }
func (r *PayloadShapingWebhookEvent) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type PayloadShapingWebhookEventEventType string

const (
	PayloadShapingWebhookEventEventTypePayloadShaping PayloadShapingWebhookEventEventType = "payload_shaping"
)

type PayloadShapingWebhookEventMetadata struct {
	DurationFunctionToEventSeconds float64 `json:"durationFunctionToEventSeconds"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		DurationFunctionToEventSeconds respjson.Field
		ExtraFields                    map[string]respjson.Field
		raw                            string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r PayloadShapingWebhookEventMetadata) RawJSON() string { return r.JSON.raw }
func (r *PayloadShapingWebhookEventMetadata) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type SendWebhookEvent struct {
	// Outcome of a Send function's delivery attempt.
	//
	// Any of "success", "skip".
	DeliveryStatus SendWebhookEventDeliveryStatus `json:"deliveryStatus" api:"required"`
	// Destination type for a Send function.
	//
	// Any of "webhook", "s3", "google_drive".
	DestinationType SendDestinationType `json:"destinationType" api:"required"`
	// Unique ID generated by bem to identify the event.
	EventID string `json:"eventID" api:"required"`
	// Unique identifier of function that this event is associated with.
	FunctionID string `json:"functionID" api:"required"`
	// Unique name of function that this event is associated with.
	FunctionName string `json:"functionName" api:"required"`
	// The unique ID you use internally to refer to this data point, propagated from
	// the original function input.
	ReferenceID string `json:"referenceID" api:"required"`
	// Unique identifier of workflow call that this event is associated with.
	CallID string `json:"callID"`
	// Timestamp indicating when the event was created.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// The full protocol event JSON that was delivered — identical to what subscription
	// publish would deliver for the same event. For ad-hoc calls with a JSON file
	// input, contains the raw input JSON. For ad-hoc calls with a binary file input,
	// contains {"s3URL": "<presigned-url>"}.
	DeliveredContent any `json:"deliveredContent"`
	// Any of "send".
	EventType SendWebhookEventEventType `json:"eventType"`
	// Unique identifier of function call that this event is associated with.
	FunctionCallID string `json:"functionCallID"`
	// The attempt number of the function call that created this event. 1 indexed.
	FunctionCallTryNumber int64 `json:"functionCallTryNumber"`
	// Version number of function that this event is associated with.
	FunctionVersionNum int64 `json:"functionVersionNum"`
	// Metadata returned when a Send function delivers to Google Drive.
	GoogleDriveOutput SendWebhookEventGoogleDriveOutput `json:"googleDriveOutput"`
	// The inbound email that triggered this event.
	InboundEmail InboundEmailEvent        `json:"inboundEmail"`
	Metadata     SendWebhookEventMetadata `json:"metadata"`
	// Metadata returned when a Send function delivers to an S3 bucket.
	S3Output SendWebhookEventS3Output `json:"s3Output"`
	// Metadata returned when a Send function delivers to a webhook.
	WebhookOutput SendWebhookEventWebhookOutput `json:"webhookOutput"`
	// Unique identifier of workflow that this event is associated with.
	WorkflowID string `json:"workflowID"`
	// Name of workflow that this event is associated with.
	WorkflowName string `json:"workflowName"`
	// Version number of workflow that this event is associated with.
	WorkflowVersionNum int64 `json:"workflowVersionNum"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		DeliveryStatus        respjson.Field
		DestinationType       respjson.Field
		EventID               respjson.Field
		FunctionID            respjson.Field
		FunctionName          respjson.Field
		ReferenceID           respjson.Field
		CallID                respjson.Field
		CreatedAt             respjson.Field
		DeliveredContent      respjson.Field
		EventType             respjson.Field
		FunctionCallID        respjson.Field
		FunctionCallTryNumber respjson.Field
		FunctionVersionNum    respjson.Field
		GoogleDriveOutput     respjson.Field
		InboundEmail          respjson.Field
		Metadata              respjson.Field
		S3Output              respjson.Field
		WebhookOutput         respjson.Field
		WorkflowID            respjson.Field
		WorkflowName          respjson.Field
		WorkflowVersionNum    respjson.Field
		ExtraFields           map[string]respjson.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SendWebhookEvent) RawJSON() string { return r.JSON.raw }
func (r *SendWebhookEvent) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Outcome of a Send function's delivery attempt.
type SendWebhookEventDeliveryStatus string

const (
	SendWebhookEventDeliveryStatusSuccess SendWebhookEventDeliveryStatus = "success"
	SendWebhookEventDeliveryStatusSkip    SendWebhookEventDeliveryStatus = "skip"
)

type SendWebhookEventEventType string

const (
	SendWebhookEventEventTypeSend SendWebhookEventEventType = "send"
)

// Metadata returned when a Send function delivers to Google Drive.
type SendWebhookEventGoogleDriveOutput struct {
	// Name of the file created in Google Drive.
	FileName string `json:"fileName" api:"required"`
	// ID of the Google Drive folder the file was placed in.
	FolderID string `json:"folderID" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		FileName    respjson.Field
		FolderID    respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SendWebhookEventGoogleDriveOutput) RawJSON() string { return r.JSON.raw }
func (r *SendWebhookEventGoogleDriveOutput) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type SendWebhookEventMetadata struct {
	DurationFunctionToEventSeconds float64 `json:"durationFunctionToEventSeconds"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		DurationFunctionToEventSeconds respjson.Field
		ExtraFields                    map[string]respjson.Field
		raw                            string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SendWebhookEventMetadata) RawJSON() string { return r.JSON.raw }
func (r *SendWebhookEventMetadata) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Metadata returned when a Send function delivers to an S3 bucket.
type SendWebhookEventS3Output struct {
	// Name of the S3 bucket the payload was written to.
	BucketName string `json:"bucketName" api:"required"`
	// Object key under which the payload was stored.
	Key string `json:"key" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		BucketName  respjson.Field
		Key         respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SendWebhookEventS3Output) RawJSON() string { return r.JSON.raw }
func (r *SendWebhookEventS3Output) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Metadata returned when a Send function delivers to a webhook.
type SendWebhookEventWebhookOutput struct {
	// Raw HTTP response body returned by the webhook endpoint.
	HTTPResponseBody string `json:"httpResponseBody" api:"required"`
	// HTTP status code returned by the webhook endpoint.
	HTTPStatusCode int64 `json:"httpStatusCode" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		HTTPResponseBody respjson.Field
		HTTPStatusCode   respjson.Field
		ExtraFields      map[string]respjson.Field
		raw              string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SendWebhookEventWebhookOutput) RawJSON() string { return r.JSON.raw }
func (r *SendWebhookEventWebhookOutput) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Emitted when a function-accuracy evaluation completes for a transformation.
// Evaluations are scheduled by `POST /v3/eval` and run asynchronously; this event
// reports the terminal result.
type EvaluationWebhookEvent struct {
	// Version identifier of the evaluation logic that produced this result.
	EvaluationVersion string `json:"evaluationVersion" api:"required"`
	// Unique ID generated by bem to identify the event.
	EventID string `json:"eventID" api:"required"`
	// Unique identifier of function that this event is associated with.
	FunctionID string `json:"functionID" api:"required"`
	// Unique name of function that this event is associated with.
	FunctionName string `json:"functionName" api:"required"`
	// The unique ID you use internally to refer to this data point, propagated from
	// the original function input.
	ReferenceID string `json:"referenceID" api:"required"`
	// Evaluator output. Shape depends on `evaluationVersion` and includes confidence
	// scores, per-field hallucination flags, and relevance metrics.
	Result any `json:"result" api:"required"`
	// Terminal status of the evaluation run.
	//
	// Any of "success", "failed".
	Status EvaluationWebhookEventStatus `json:"status" api:"required"`
	// Unique ID of the transformation that was evaluated.
	TransformID string `json:"transformId" api:"required"`
	// Unique identifier of workflow call that this event is associated with.
	CallID string `json:"callID"`
	// Timestamp indicating when the event was created.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// Failure reason populated when `status` is `failed`.
	ErrorMessage string `json:"errorMessage"`
	// Any of "evaluation".
	EventType EvaluationWebhookEventEventType `json:"eventType"`
	// Unique identifier of function call that this event is associated with.
	FunctionCallID string `json:"functionCallID"`
	// The attempt number of the function call that created this event. 1 indexed.
	FunctionCallTryNumber int64 `json:"functionCallTryNumber"`
	// Version number of function that this event is associated with.
	FunctionVersionNum int64 `json:"functionVersionNum"`
	// The inbound email that triggered this event.
	InboundEmail InboundEmailEvent              `json:"inboundEmail"`
	Metadata     EvaluationWebhookEventMetadata `json:"metadata"`
	// Unique identifier of workflow that this event is associated with.
	WorkflowID string `json:"workflowID"`
	// Name of workflow that this event is associated with.
	WorkflowName string `json:"workflowName"`
	// Version number of workflow that this event is associated with.
	WorkflowVersionNum int64 `json:"workflowVersionNum"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		EvaluationVersion     respjson.Field
		EventID               respjson.Field
		FunctionID            respjson.Field
		FunctionName          respjson.Field
		ReferenceID           respjson.Field
		Result                respjson.Field
		Status                respjson.Field
		TransformID           respjson.Field
		CallID                respjson.Field
		CreatedAt             respjson.Field
		ErrorMessage          respjson.Field
		EventType             respjson.Field
		FunctionCallID        respjson.Field
		FunctionCallTryNumber respjson.Field
		FunctionVersionNum    respjson.Field
		InboundEmail          respjson.Field
		Metadata              respjson.Field
		WorkflowID            respjson.Field
		WorkflowName          respjson.Field
		WorkflowVersionNum    respjson.Field
		ExtraFields           map[string]respjson.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r EvaluationWebhookEvent) RawJSON() string { return r.JSON.raw }
func (r *EvaluationWebhookEvent) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Terminal status of the evaluation run.
type EvaluationWebhookEventStatus string

const (
	EvaluationWebhookEventStatusSuccess EvaluationWebhookEventStatus = "success"
	EvaluationWebhookEventStatusFailed  EvaluationWebhookEventStatus = "failed"
)

type EvaluationWebhookEventEventType string

const (
	EvaluationWebhookEventEventTypeEvaluation EvaluationWebhookEventEventType = "evaluation"
)

type EvaluationWebhookEventMetadata struct {
	DurationFunctionToEventSeconds float64 `json:"durationFunctionToEventSeconds"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		DurationFunctionToEventSeconds respjson.Field
		ExtraFields                    map[string]respjson.Field
		raw                            string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r EvaluationWebhookEventMetadata) RawJSON() string { return r.JSON.raw }
func (r *EvaluationWebhookEventMetadata) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type CollectionProcessingWebhookEvent struct {
	// Unique identifier of the collection.
	CollectionID string `json:"collectionID" api:"required"`
	// Name/path of the collection.
	CollectionName string `json:"collectionName" api:"required"`
	// Unique ID generated by bem to identify the event.
	EventID string `json:"eventID" api:"required"`
	// The operation performed (add or update).
	//
	// Any of "add", "update".
	Operation CollectionProcessingWebhookEventOperation `json:"operation" api:"required"`
	// Number of items successfully processed.
	ProcessedCount int64 `json:"processedCount" api:"required"`
	// The unique ID you use internally to refer to this data point, propagated from
	// the original function input.
	ReferenceID string `json:"referenceID" api:"required"`
	// Processing status (success or failed).
	//
	// Any of "success", "failed".
	Status CollectionProcessingWebhookEventStatus `json:"status" api:"required"`
	// Array of collection item KSUIDs that were added or updated.
	CollectionItemIDs []string `json:"collectionItemIDs"`
	// Timestamp indicating when the event was created.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// Error message if processing failed.
	ErrorMessage string `json:"errorMessage"`
	// Any of "collection_processing".
	EventType CollectionProcessingWebhookEventEventType `json:"eventType"`
	// The attempt number of the function call that created this event. 1 indexed.
	FunctionCallTryNumber int64 `json:"functionCallTryNumber"`
	// The inbound email that triggered this event.
	InboundEmail InboundEmailEvent                        `json:"inboundEmail"`
	Metadata     CollectionProcessingWebhookEventMetadata `json:"metadata"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		CollectionID          respjson.Field
		CollectionName        respjson.Field
		EventID               respjson.Field
		Operation             respjson.Field
		ProcessedCount        respjson.Field
		ReferenceID           respjson.Field
		Status                respjson.Field
		CollectionItemIDs     respjson.Field
		CreatedAt             respjson.Field
		ErrorMessage          respjson.Field
		EventType             respjson.Field
		FunctionCallTryNumber respjson.Field
		InboundEmail          respjson.Field
		Metadata              respjson.Field
		ExtraFields           map[string]respjson.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r CollectionProcessingWebhookEvent) RawJSON() string { return r.JSON.raw }
func (r *CollectionProcessingWebhookEvent) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// The operation performed (add or update).
type CollectionProcessingWebhookEventOperation string

const (
	CollectionProcessingWebhookEventOperationAdd    CollectionProcessingWebhookEventOperation = "add"
	CollectionProcessingWebhookEventOperationUpdate CollectionProcessingWebhookEventOperation = "update"
)

// Processing status (success or failed).
type CollectionProcessingWebhookEventStatus string

const (
	CollectionProcessingWebhookEventStatusSuccess CollectionProcessingWebhookEventStatus = "success"
	CollectionProcessingWebhookEventStatusFailed  CollectionProcessingWebhookEventStatus = "failed"
)

type CollectionProcessingWebhookEventEventType string

const (
	CollectionProcessingWebhookEventEventTypeCollectionProcessing CollectionProcessingWebhookEventEventType = "collection_processing"
)

type CollectionProcessingWebhookEventMetadata struct {
	DurationFunctionToEventSeconds float64 `json:"durationFunctionToEventSeconds"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		DurationFunctionToEventSeconds respjson.Field
		ExtraFields                    map[string]respjson.Field
		raw                            string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r CollectionProcessingWebhookEventMetadata) RawJSON() string { return r.JSON.raw }
func (r *CollectionProcessingWebhookEventMetadata) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// UnwrapWebhookEventUnion contains all possible properties and values from
// [ExtractWebhookEvent], [ClassifyWebhookEvent], [ParseWebhookEvent],
// [SplitCollectionWebhookEvent], [SplitItemWebhookEvent], [JoinWebhookEvent],
// [EnrichWebhookEvent], [PayloadShapingWebhookEvent], [SendWebhookEvent],
// [EvaluationWebhookEvent], [CollectionProcessingWebhookEvent], [ErrorEvent].
//
// Use the [UnwrapWebhookEventUnion.AsAny] method to switch on the variant.
//
// Use the methods beginning with 'As' to cast the union to one of its variants.
type UnwrapWebhookEventUnion struct {
	EventID            string  `json:"eventID"`
	FunctionID         string  `json:"functionID"`
	FunctionName       string  `json:"functionName"`
	ItemCount          int64   `json:"itemCount"`
	ItemOffset         int64   `json:"itemOffset"`
	ReferenceID        string  `json:"referenceID"`
	TransformedContent any     `json:"transformedContent"`
	AvgConfidence      float64 `json:"avgConfidence"`
	CallID             string  `json:"callID"`
	// This field is a union of [ExtractWebhookEventCorrectedContentUnion],
	// [ParseWebhookEventCorrectedContentUnion]
	CorrectedContent UnwrapWebhookEventUnionCorrectedContent `json:"correctedContent"`
	CreatedAt        time.Time                               `json:"createdAt"`
	// Any of "extract", "classify", "parse", "split_collection", "split_item", "join",
	// "enrich", "payload_shaping", "send", "evaluation", "collection_processing",
	// "error".
	EventType             string `json:"eventType"`
	FieldBoundingBoxes    any    `json:"fieldBoundingBoxes"`
	FieldConfidences      any    `json:"fieldConfidences"`
	FunctionCallID        string `json:"functionCallID"`
	FunctionCallTryNumber int64  `json:"functionCallTryNumber"`
	FunctionVersionNum    int64  `json:"functionVersionNum"`
	// This field is from variant [ExtractWebhookEvent].
	InboundEmail InboundEmailEvent `json:"inboundEmail"`
	// This field is a union of [[]ExtractWebhookEventInput],
	// [[]ParseWebhookEventInput]
	Inputs UnwrapWebhookEventUnionInputs `json:"inputs"`
	// This field is from variant [ExtractWebhookEvent].
	InputType         InputType `json:"inputType"`
	InvalidProperties []string  `json:"invalidProperties"`
	// This field is a union of [ExtractWebhookEventMetadata],
	// [ClassifyWebhookEventMetadata], [ParseWebhookEventMetadata],
	// [SplitCollectionWebhookEventMetadata], [SplitItemWebhookEventMetadata],
	// [JoinWebhookEventMetadata], [EnrichWebhookEventMetadata],
	// [PayloadShapingWebhookEventMetadata], [SendWebhookEventMetadata],
	// [EvaluationWebhookEventMetadata], [CollectionProcessingWebhookEventMetadata],
	// [ErrorEventMetadata]
	Metadata           UnwrapWebhookEventUnionMetadata `json:"metadata"`
	S3URL              string                          `json:"s3URL"`
	TransformationID   string                          `json:"transformationID"`
	WorkflowID         string                          `json:"workflowID"`
	WorkflowName       string                          `json:"workflowName"`
	WorkflowVersionNum int64                           `json:"workflowVersionNum"`
	// This field is from variant [ClassifyWebhookEvent].
	Choice     string `json:"choice"`
	OutputType string `json:"outputType"`
	// This field is a union of [SplitCollectionWebhookEventPrintPageOutput],
	// [SplitItemWebhookEventPrintPageOutput]
	PrintPageOutput UnwrapWebhookEventUnionPrintPageOutput `json:"printPageOutput"`
	// This field is a union of [SplitCollectionWebhookEventSemanticPageOutput],
	// [SplitItemWebhookEventSemanticPageOutput]
	SemanticPageOutput UnwrapWebhookEventUnionSemanticPageOutput `json:"semanticPageOutput"`
	// This field is from variant [JoinWebhookEvent].
	Items []JoinWebhookEventItem `json:"items"`
	// This field is from variant [JoinWebhookEvent].
	JoinType JoinWebhookEventJoinType `json:"joinType"`
	// This field is from variant [EnrichWebhookEvent].
	EnrichedContent any `json:"enrichedContent"`
	// This field is from variant [EnrichWebhookEvent].
	GroundTruth any `json:"groundTruth"`
	// This field is from variant [SendWebhookEvent].
	DeliveryStatus SendWebhookEventDeliveryStatus `json:"deliveryStatus"`
	// This field is from variant [SendWebhookEvent].
	DestinationType SendDestinationType `json:"destinationType"`
	// This field is from variant [SendWebhookEvent].
	DeliveredContent any `json:"deliveredContent"`
	// This field is from variant [SendWebhookEvent].
	GoogleDriveOutput SendWebhookEventGoogleDriveOutput `json:"googleDriveOutput"`
	// This field is from variant [SendWebhookEvent].
	S3Output SendWebhookEventS3Output `json:"s3Output"`
	// This field is from variant [SendWebhookEvent].
	WebhookOutput SendWebhookEventWebhookOutput `json:"webhookOutput"`
	// This field is from variant [EvaluationWebhookEvent].
	EvaluationVersion string `json:"evaluationVersion"`
	// This field is from variant [EvaluationWebhookEvent].
	Result any    `json:"result"`
	Status string `json:"status"`
	// This field is from variant [EvaluationWebhookEvent].
	TransformID  string `json:"transformId"`
	ErrorMessage string `json:"errorMessage"`
	// This field is from variant [CollectionProcessingWebhookEvent].
	CollectionID string `json:"collectionID"`
	// This field is from variant [CollectionProcessingWebhookEvent].
	CollectionName string `json:"collectionName"`
	// This field is from variant [CollectionProcessingWebhookEvent].
	Operation CollectionProcessingWebhookEventOperation `json:"operation"`
	// This field is from variant [CollectionProcessingWebhookEvent].
	ProcessedCount int64 `json:"processedCount"`
	// This field is from variant [CollectionProcessingWebhookEvent].
	CollectionItemIDs []string `json:"collectionItemIDs"`
	// This field is from variant [ErrorEvent].
	Message string `json:"message"`
	// This field is from variant [ErrorEvent].
	Kind string `json:"kind"`
	JSON struct {
		EventID               respjson.Field
		FunctionID            respjson.Field
		FunctionName          respjson.Field
		ItemCount             respjson.Field
		ItemOffset            respjson.Field
		ReferenceID           respjson.Field
		TransformedContent    respjson.Field
		AvgConfidence         respjson.Field
		CallID                respjson.Field
		CorrectedContent      respjson.Field
		CreatedAt             respjson.Field
		EventType             respjson.Field
		FieldBoundingBoxes    respjson.Field
		FieldConfidences      respjson.Field
		FunctionCallID        respjson.Field
		FunctionCallTryNumber respjson.Field
		FunctionVersionNum    respjson.Field
		InboundEmail          respjson.Field
		Inputs                respjson.Field
		InputType             respjson.Field
		InvalidProperties     respjson.Field
		Metadata              respjson.Field
		S3URL                 respjson.Field
		TransformationID      respjson.Field
		WorkflowID            respjson.Field
		WorkflowName          respjson.Field
		WorkflowVersionNum    respjson.Field
		Choice                respjson.Field
		OutputType            respjson.Field
		PrintPageOutput       respjson.Field
		SemanticPageOutput    respjson.Field
		Items                 respjson.Field
		JoinType              respjson.Field
		EnrichedContent       respjson.Field
		GroundTruth           respjson.Field
		DeliveryStatus        respjson.Field
		DestinationType       respjson.Field
		DeliveredContent      respjson.Field
		GoogleDriveOutput     respjson.Field
		S3Output              respjson.Field
		WebhookOutput         respjson.Field
		EvaluationVersion     respjson.Field
		Result                respjson.Field
		Status                respjson.Field
		TransformID           respjson.Field
		ErrorMessage          respjson.Field
		CollectionID          respjson.Field
		CollectionName        respjson.Field
		Operation             respjson.Field
		ProcessedCount        respjson.Field
		CollectionItemIDs     respjson.Field
		Message               respjson.Field
		Kind                  respjson.Field
		raw                   string
	} `json:"-"`
}

// anyUnwrapWebhookEvent is implemented by each variant of
// [UnwrapWebhookEventUnion] to add type safety for the return type of
// [UnwrapWebhookEventUnion.AsAny]
type anyUnwrapWebhookEvent interface {
	implUnwrapWebhookEventUnion()
}

func (ExtractWebhookEvent) implUnwrapWebhookEventUnion()              {}
func (ClassifyWebhookEvent) implUnwrapWebhookEventUnion()             {}
func (ParseWebhookEvent) implUnwrapWebhookEventUnion()                {}
func (SplitCollectionWebhookEvent) implUnwrapWebhookEventUnion()      {}
func (SplitItemWebhookEvent) implUnwrapWebhookEventUnion()            {}
func (JoinWebhookEvent) implUnwrapWebhookEventUnion()                 {}
func (EnrichWebhookEvent) implUnwrapWebhookEventUnion()               {}
func (PayloadShapingWebhookEvent) implUnwrapWebhookEventUnion()       {}
func (SendWebhookEvent) implUnwrapWebhookEventUnion()                 {}
func (EvaluationWebhookEvent) implUnwrapWebhookEventUnion()           {}
func (CollectionProcessingWebhookEvent) implUnwrapWebhookEventUnion() {}
func (ErrorEvent) implUnwrapWebhookEventUnion()                       {}

// Use the following switch statement to find the correct variant
//
//	switch variant := UnwrapWebhookEventUnion.AsAny().(type) {
//	case bem.ExtractWebhookEvent:
//	case bem.ClassifyWebhookEvent:
//	case bem.ParseWebhookEvent:
//	case bem.SplitCollectionWebhookEvent:
//	case bem.SplitItemWebhookEvent:
//	case bem.JoinWebhookEvent:
//	case bem.EnrichWebhookEvent:
//	case bem.PayloadShapingWebhookEvent:
//	case bem.SendWebhookEvent:
//	case bem.EvaluationWebhookEvent:
//	case bem.CollectionProcessingWebhookEvent:
//	case bem.ErrorEvent:
//	default:
//	  fmt.Errorf("no variant present")
//	}
func (u UnwrapWebhookEventUnion) AsAny() anyUnwrapWebhookEvent {
	switch u.EventType {
	case "extract":
		return u.AsExtract()
	case "classify":
		return u.AsClassify()
	case "parse":
		return u.AsParse()
	case "split_collection":
		return u.AsSplitCollection()
	case "split_item":
		return u.AsSplitItem()
	case "join":
		return u.AsJoin()
	case "enrich":
		return u.AsEnrich()
	case "payload_shaping":
		return u.AsPayloadShaping()
	case "send":
		return u.AsSend()
	case "evaluation":
		return u.AsEvaluation()
	case "collection_processing":
		return u.AsCollectionProcessing()
	case "error":
		return u.AsError()
	}
	return nil
}

func (u UnwrapWebhookEventUnion) AsExtract() (v ExtractWebhookEvent) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u UnwrapWebhookEventUnion) AsClassify() (v ClassifyWebhookEvent) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u UnwrapWebhookEventUnion) AsParse() (v ParseWebhookEvent) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u UnwrapWebhookEventUnion) AsSplitCollection() (v SplitCollectionWebhookEvent) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u UnwrapWebhookEventUnion) AsSplitItem() (v SplitItemWebhookEvent) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u UnwrapWebhookEventUnion) AsJoin() (v JoinWebhookEvent) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u UnwrapWebhookEventUnion) AsEnrich() (v EnrichWebhookEvent) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u UnwrapWebhookEventUnion) AsPayloadShaping() (v PayloadShapingWebhookEvent) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u UnwrapWebhookEventUnion) AsSend() (v SendWebhookEvent) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u UnwrapWebhookEventUnion) AsEvaluation() (v EvaluationWebhookEvent) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u UnwrapWebhookEventUnion) AsCollectionProcessing() (v CollectionProcessingWebhookEvent) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

func (u UnwrapWebhookEventUnion) AsError() (v ErrorEvent) {
	apijson.UnmarshalRoot(json.RawMessage(u.JSON.raw), &v)
	return
}

// Returns the unmodified JSON received from the API
func (u UnwrapWebhookEventUnion) RawJSON() string { return u.JSON.raw }

func (r *UnwrapWebhookEventUnion) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// UnwrapWebhookEventUnionCorrectedContent is an implicit subunion of
// [UnwrapWebhookEventUnion]. UnwrapWebhookEventUnionCorrectedContent provides
// convenient access to the sub-properties of the union.
//
// For type safety it is recommended to directly use a variant of the
// [UnwrapWebhookEventUnion].
//
// If the underlying value is not a json object, one of the following properties
// will be valid: OfAnyArray OfString OfFloat OfBool]
type UnwrapWebhookEventUnionCorrectedContent struct {
	// This field will be present if the value is a [[]any] instead of an object.
	OfAnyArray []any `json:",inline"`
	// This field will be present if the value is a [string] instead of an object.
	OfString string `json:",inline"`
	// This field will be present if the value is a [float64] instead of an object.
	OfFloat float64 `json:",inline"`
	// This field will be present if the value is a [bool] instead of an object.
	OfBool bool           `json:",inline"`
	Output []AnyTypeUnion `json:"output"`
	JSON   struct {
		OfAnyArray respjson.Field
		OfString   respjson.Field
		OfFloat    respjson.Field
		OfBool     respjson.Field
		Output     respjson.Field
		raw        string
	} `json:"-"`
}

func (r *UnwrapWebhookEventUnionCorrectedContent) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// UnwrapWebhookEventUnionInputs is an implicit subunion of
// [UnwrapWebhookEventUnion]. UnwrapWebhookEventUnionInputs provides convenient
// access to the sub-properties of the union.
//
// For type safety it is recommended to directly use a variant of the
// [UnwrapWebhookEventUnion].
//
// If the underlying value is not a json object, one of the following properties
// will be valid: OfExtractWebhookEventInputs OfParseWebhookEventInputs]
type UnwrapWebhookEventUnionInputs struct {
	// This field will be present if the value is a [[]ExtractWebhookEventInput]
	// instead of an object.
	OfExtractWebhookEventInputs []ExtractWebhookEventInput `json:",inline"`
	// This field will be present if the value is a [[]ParseWebhookEventInput] instead
	// of an object.
	OfParseWebhookEventInputs []ParseWebhookEventInput `json:",inline"`
	JSON                      struct {
		OfExtractWebhookEventInputs respjson.Field
		OfParseWebhookEventInputs   respjson.Field
		raw                         string
	} `json:"-"`
}

func (r *UnwrapWebhookEventUnionInputs) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// UnwrapWebhookEventUnionMetadata is an implicit subunion of
// [UnwrapWebhookEventUnion]. UnwrapWebhookEventUnionMetadata provides convenient
// access to the sub-properties of the union.
//
// For type safety it is recommended to directly use a variant of the
// [UnwrapWebhookEventUnion].
type UnwrapWebhookEventUnionMetadata struct {
	DurationFunctionToEventSeconds float64 `json:"durationFunctionToEventSeconds"`
	JSON                           struct {
		DurationFunctionToEventSeconds respjson.Field
		raw                            string
	} `json:"-"`
}

func (r *UnwrapWebhookEventUnionMetadata) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// UnwrapWebhookEventUnionPrintPageOutput is an implicit subunion of
// [UnwrapWebhookEventUnion]. UnwrapWebhookEventUnionPrintPageOutput provides
// convenient access to the sub-properties of the union.
//
// For type safety it is recommended to directly use a variant of the
// [UnwrapWebhookEventUnion].
type UnwrapWebhookEventUnionPrintPageOutput struct {
	ItemCount int64 `json:"itemCount"`
	// This field is from variant [SplitCollectionWebhookEventPrintPageOutput].
	Items []SplitCollectionWebhookEventPrintPageOutputItem `json:"items"`
	// This field is from variant [SplitItemWebhookEventPrintPageOutput].
	CollectionReferenceID string `json:"collectionReferenceID"`
	// This field is from variant [SplitItemWebhookEventPrintPageOutput].
	ItemOffset int64 `json:"itemOffset"`
	// This field is from variant [SplitItemWebhookEventPrintPageOutput].
	S3URL string `json:"s3URL"`
	JSON  struct {
		ItemCount             respjson.Field
		Items                 respjson.Field
		CollectionReferenceID respjson.Field
		ItemOffset            respjson.Field
		S3URL                 respjson.Field
		raw                   string
	} `json:"-"`
}

func (r *UnwrapWebhookEventUnionPrintPageOutput) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// UnwrapWebhookEventUnionSemanticPageOutput is an implicit subunion of
// [UnwrapWebhookEventUnion]. UnwrapWebhookEventUnionSemanticPageOutput provides
// convenient access to the sub-properties of the union.
//
// For type safety it is recommended to directly use a variant of the
// [UnwrapWebhookEventUnion].
type UnwrapWebhookEventUnionSemanticPageOutput struct {
	ItemCount int64 `json:"itemCount"`
	// This field is from variant [SplitCollectionWebhookEventSemanticPageOutput].
	Items     []SplitCollectionWebhookEventSemanticPageOutputItem `json:"items"`
	PageCount int64                                               `json:"pageCount"`
	// This field is from variant [SplitItemWebhookEventSemanticPageOutput].
	CollectionReferenceID string `json:"collectionReferenceID"`
	// This field is from variant [SplitItemWebhookEventSemanticPageOutput].
	ItemClass string `json:"itemClass"`
	// This field is from variant [SplitItemWebhookEventSemanticPageOutput].
	ItemClassCount int64 `json:"itemClassCount"`
	// This field is from variant [SplitItemWebhookEventSemanticPageOutput].
	ItemClassOffset int64 `json:"itemClassOffset"`
	// This field is from variant [SplitItemWebhookEventSemanticPageOutput].
	ItemOffset int64 `json:"itemOffset"`
	// This field is from variant [SplitItemWebhookEventSemanticPageOutput].
	PageEnd int64 `json:"pageEnd"`
	// This field is from variant [SplitItemWebhookEventSemanticPageOutput].
	PageStart int64 `json:"pageStart"`
	// This field is from variant [SplitItemWebhookEventSemanticPageOutput].
	S3URL string `json:"s3URL"`
	JSON  struct {
		ItemCount             respjson.Field
		Items                 respjson.Field
		PageCount             respjson.Field
		CollectionReferenceID respjson.Field
		ItemClass             respjson.Field
		ItemClassCount        respjson.Field
		ItemClassOffset       respjson.Field
		ItemOffset            respjson.Field
		PageEnd               respjson.Field
		PageStart             respjson.Field
		S3URL                 respjson.Field
		raw                   string
	} `json:"-"`
}

func (r *UnwrapWebhookEventUnionSemanticPageOutput) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}
